const fs = require('fs');
const path = require('path');

const root = process.cwd();
const docsDir = path.join(root, 'docs');
const checkOnly = process.argv.includes('--check');

const languages = [
  { code: 'de', name: 'Deutsch' },
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'hi', name: 'Hindi' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'it', name: 'Italian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
  { code: 'sk', name: 'Slovak' },
  { code: 'tr', name: 'Turkish' },
  { code: 'zh', name: 'Chinese' }
];

const docSets = [
  {
    baseFile: 'WEBAPP-DOCUMENTATION.md',
    localizedPrefix: 'WEBAPP-DOCUMENTATION',
    title: 'Web Application Documentation'
  },
  {
    baseFile: 'API-DOCUMENTATION.md',
    localizedPrefix: 'API-DOCUMENTATION',
    title: 'API Documentation'
  },
  {
    baseFile: 'SQL-DATABASE-DOCUMENTATION.md',
    localizedPrefix: 'SQL-DATABASE-DOCUMENTATION',
    title: 'SQL Database Documentation'
  }
];

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n');
}

function writeText(filePath, content) {
  fs.writeFileSync(filePath, content.replace(/\n/g, '\r\n'), 'utf8');
}

function ensureDocsDir() {
  if (!fs.existsSync(docsDir)) {
    throw new Error(`Missing docs directory: ${docsDir}`);
  }
}

function stripFirstHeading(text) {
  const lines = text.split('\n');
  if (lines.length > 0 && lines[0].startsWith('# ')) {
    return lines.slice(1).join('\n').replace(/^\n+/, '');
  }
  return text;
}

function buildLocalizedContent(set, language, baseContent) {
  const body = stripFirstHeading(baseContent).trim();
  return [
    `# ${set.title} (${language.name})`,
    '',
    `> Auto-generated from ${set.baseFile}.`,
    '> Source of truth: the base documentation file listed above.',
    '> Regenerate with: npm run docs:sync',
    '',
    body,
    ''
  ].join('\n');
}

function buildIndexContent() {
  const lines = [];
  lines.push('# Documentation Index');
  lines.push('');
  lines.push('This index is auto-generated by scripts/sync-docs.js.');
  lines.push('');

  for (const set of docSets) {
    lines.push(`## ${set.title}`);
    lines.push(`- ${set.baseFile}`);
    for (const language of languages) {
      lines.push(`- ${set.localizedPrefix}.${language.code}.md`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trim()}\n`;
}

function assertOrWrite(targetPath, nextContent, changedFiles) {
  if (!fs.existsSync(targetPath)) {
    if (checkOnly) {
      changedFiles.push(targetPath);
      return;
    }
    writeText(targetPath, nextContent);
    changedFiles.push(targetPath);
    return;
  }

  const current = readText(targetPath);
  if (current !== nextContent) {
    if (checkOnly) {
      changedFiles.push(targetPath);
      return;
    }
    writeText(targetPath, nextContent);
    changedFiles.push(targetPath);
  }
}

function main() {
  ensureDocsDir();

  const changedFiles = [];

  for (const set of docSets) {
    const basePath = path.join(docsDir, set.baseFile);
    if (!fs.existsSync(basePath)) {
      throw new Error(`Missing base documentation file: ${basePath}`);
    }
    const baseContent = readText(basePath);

    for (const language of languages) {
      const localizedName = `${set.localizedPrefix}.${language.code}.md`;
      const localizedPath = path.join(docsDir, localizedName);
      const localizedContent = buildLocalizedContent(set, language, baseContent);
      assertOrWrite(localizedPath, localizedContent, changedFiles);
    }
  }

  const indexPath = path.join(docsDir, 'DOCUMENTATION-INDEX.md');
  const indexContent = buildIndexContent();
  assertOrWrite(indexPath, indexContent, changedFiles);

  if (checkOnly) {
    if (changedFiles.length > 0) {
      console.error('Documentation is out of date. Run: npm run docs:sync');
      for (const file of changedFiles) {
        console.error(`- ${path.relative(root, file)}`);
      }
      process.exit(1);
    }
    console.log('Documentation is up to date.');
    return;
  }

  if (changedFiles.length === 0) {
    console.log('No documentation changes required.');
    return;
  }

  console.log('Updated documentation files:');
  for (const file of changedFiles) {
    console.log(`- ${path.relative(root, file)}`);
  }
}

main();
